# Generated by Django 2.0 on 2018-04-10 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flat', '0001_initial'),
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room_Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_time', models.DateTimeField(unique=True)),
                ('temperature', models.FloatField(null=True)),
                ('humidity', models.FloatField(null=True)),
                ('amount_of_CO2', models.FloatField(null=True)),
                ('flat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flat.Flat')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.Room')),
            ],
        ),
    ]
