# Generated by Django 2.0.6 on 2018-10-10 12:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movement_reading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movementreading',
            name='reading_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
