# Generated by Django 2.0.6 on 2018-10-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movement_reading', '0002_movementreading_reading_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movementreading',
            name='reading_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
