# Generated by Django 2.0 on 2018-04-10 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensor', '0001_initial'),
        ('unit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor_Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('which_appliance', models.CharField(max_length=45)),
                ('sensor_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sensor.Sensor')),
                ('unit_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='unit.Unit')),
            ],
        ),
    ]
