# Generated by Django 2.0.6 on 2018-10-10 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=45, unique=True)),
                ('room_name', models.CharField(max_length=45)),
                ('last_humidity', models.FloatField(null=True)),
                ('last_temperature', models.FloatField(null=True)),
                ('last_amount_CO2', models.FloatField(null=True)),
                ('last_reading_time', models.DateTimeField()),
                ('nr_of_appliances', models.IntegerField()),
                ('flat_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flat.Flat')),
            ],
        ),
    ]
