# Generated by Django 2.0 on 2018-04-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_for', models.CharField(max_length=45)),
                ('unit', models.CharField(max_length=45)),
            ],
        ),
    ]
