# Generated by Django 2.0 on 2018-04-10 10:50

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flat', '0001_initial'),
        ('personal_details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person_Sleep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('sleep_from', models.DateTimeField()),
                ('sleep_till', models.DateTimeField()),
                ('duration', models.TimeField()),
                ('flat_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flat.Flat')),
                ('personId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='personal_details.Personal_details')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
