# Generated by Django 2.0 on 2018-04-10 10:50

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('building', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('reading_time', models.DateTimeField()),
                ('temperature', models.FloatField(null=True)),
                ('humidity', models.FloatField(null=True)),
                ('windspeed', models.IntegerField()),
                ('wind_direction', models.IntegerField()),
                ('solar_rediation', models.FloatField(null=True)),
                ('amount_of_CO2', models.FloatField(null=True)),
                ('building_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building.Building')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
