# Generated by Django 2.0 on 2018-04-10 10:50

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appliance_in_building', '0001_initial'),
        ('flat', '0001_initial'),
        ('room', '0001_initial'),
        ('appliance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance_Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('reading_time', models.DateTimeField(unique=True)),
                ('appliance_energy_consumed', models.FloatField(null=True)),
                ('cold_water_reading', models.FloatField(null=True)),
                ('hot_water_reading', models.FloatField(null=True)),
                ('appliance_id', models.ForeignKey(max_length=45, on_delete=django.db.models.deletion.CASCADE, to='appliance.Appliance')),
                ('appliance_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appliance_in_building.List_Of_All_Appliance_in_building')),
                ('flat_id', models.OneToOneField(max_length=45, on_delete=django.db.models.deletion.CASCADE, to='flat.Flat')),
                ('room_id', models.OneToOneField(max_length=45, on_delete=django.db.models.deletion.CASCADE, to='room.Room')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
