# Generated by Django 2.0 on 2018-04-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=45)),
                ('postcode', models.CharField(max_length=45)),
                ('country', models.CharField(max_length=45)),
                ('nr_Of_Floors', models.IntegerField()),
                ('building_name', models.CharField(max_length=45)),
            ],
        ),
    ]
